version: '3.7'

services:
  mail:
    image: ${IMAGE_NAME:-marvambass/versatile-postfix}:${IMAGE_TAG:-latest}
    command: ${PUBLIC_HOSTNAME} ${MAIL_USER}:${MAIL_PASS}
    environment:
      - POSTFIX_RAW_CONFIG_MYNETWORKS=${MAIL_NETWORKS:-127.0.0.0/8 10.0.0.0/8 172.0.0.0/8}
      - ALIASES=postmaster:${MAIL_USER};hostmaster:${MAIL_USER};webmaster:${MAIL_USER};admin:${MAIL_USER};abuse:${MAIL_USER};${MAIL_USER}:${EXTERNAL_EMAIL_ADDRESS};${ADDITIONAL_ALIASES}
    networks:
      - mail-net
    ports:
      - target: 25
        published: ${MAIL_PORT:-25}
        mode: ${MAIL_PORT_MODE:-host}
    volumes:
      - mail-vol:/var/mail
      - dkim-vol:/etc/postfix/dkim/
    deploy:
      mode: replicated
      replicas: ${MAIL_REPLICAS:-1}
      restart_policy:
        delay: ${MAIL_RESTART_POLICY_DELAY:-10s}
        window: ${MAIL_RESTART_POLICY_WINDOW:-1m}
      resources:
        limits:
          cpus: "${MAIL_LIMITS_CPUS:-0.1}"
          memory: ${MAIL_LIMITS_MEMORY:-32M}
        reservations:
          memory: ${MAIL_RESERVATIONS_MEMORY:-16M}

networks:
  mail-net:
    name: ${MAIL_NET_NAME:-mail-net}
    driver: overlay
    attachable: ${MAIL_NET_ATTACHABLE:-true}

volumes:
  mail-vol:
    name: ${MAIL_VOL_NAME:-mail-vol}

  dkim-vol:
    name: ${DKIM_VOL_NAME:-dkim-vol}
