version: '3.7'

services:
  mail:
    image: ${IMAGE_NAME:-marvambass/versatile-postfix}:${IMAGE_TAG:-latest}
    command: ${PUBLIC_HOSTNAME} ${MAIL_USER}:${MAIL_PASS}
    hostname: ${PUBLIC_HOSTNAME}
    environment:
      ALIASES: postmaster:${MAIL_USER};hostmaster:${MAIL_USER};webmaster:${MAIL_USER};admin:${MAIL_USER};abuse:${MAIL_USER};root:${MAIL_USER};${MAIL_USER}:${EXTERNAL_EMAIL_ADDRESS};${ADDITIONAL_ALIASES}
      POSTFIX_RAW_CONFIG_MYNETWORKS:
      POSTFIX_RAW_CONFIG_SMTPD_CLIENT_RESTRICTIONS:
      POSTFIX_RAW_CONFIG_SMTPD_HELO_RESTRICTIONS:
      POSTFIX_RAW_CONFIG_SMTPD_SENDER_RESTRICTIONS:
      POSTFIX_RAW_CONFIG_SMTPD_RECIPIENT_RESTRICTIONS:
      POSTFIX_RAW_CONFIG_SMTPD_RELAY_RESTRICTIONS:
      POSTFIX_RAW_CONFIG_SMTPD_DATA_RESTRICTIONS:
    networks:
      mail-net:
    ports:
      - target: ${INTERNAL_PORT}
        published: ${PORT1}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${INTERNAL_PORT}
        published: ${PORT1}
        protocol: udp
        mode: ${PORT_MODE}
      - target: ${INTERNAL_PORT}
        published: ${PORT2}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${INTERNAL_PORT}
        published: ${PORT2}
        protocol: udp
        mode: ${PORT_MODE}
      - target: ${INTERNAL_PORT}
        published: ${PORT3}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${INTERNAL_PORT}
        published: ${PORT3}
        protocol: udp
        mode: ${PORT_MODE}
    volumes:
      - data-vol:/var/mail
      - dkim-vol:/etc/postfix/dkim/
      - log-vol:/var/log
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      placement:
        constraints:
          - ${PLACEMENT_CONSTRAINT:-node.hostname == node}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-8M}

networks:
  mail-net:
    name: ${MAIL_NET_NAME:-mail-net}
    driver: ${MAIL_NET_DRIVER:-overlay}
    attachable: ${MAIL_NET_ATTACHABLE:-true}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-mail-data-vol}

  dkim-vol:
    name: ${DKIM_VOL_NAME:-mail-dkim-vol}

  log-vol:
    name: ${LOG_VOL_NAME:-mail-log-vol}
