version: '3.7'

services:
  mail:
    image: ${IMAGE_NAME:-marvambass/versatile-postfix}:${IMAGE_TAG:-latest}
    command: ${PUBLIC_HOSTNAME} ${MAIL_USER}:${MAIL_PASS}
    environment:
      ALIASES: postmaster:${MAIL_USER};hostmaster:${MAIL_USER};webmaster:${MAIL_USER};admin:${MAIL_USER};abuse:${MAIL_USER};${MAIL_USER}:${EXTERNAL_EMAIL_ADDRESS};${ADDITIONAL_ALIASES}
      POSTFIX_RAW_CONFIG_SMTPD_HELO_RESTRICTIONS:
    networks:
      - mail-net
    ports:
      - target: 25
        published: ${MAIL_PORT}
        protocol: tcp
        mode: ${MAIL_PORT_MODE}
      - target: 25
        published: ${MAIL_PORT}
        protocol: udp
        mode: ${MAIL_PORT_MODE}
    volumes:
      - data-vol:/var/mail
      - dkim-vol:/etc/postfix/dkim/
      - log-vol:/var/log
    deploy:
      mode: replicated
      replicas: ${MAIL_REPLICAS:-1}
      restart_policy:
        delay: ${MAIL_RESTART_POLICY_DELAY:-10s}
        window: ${MAIL_RESTART_POLICY_WINDOW:-1m}
      placement:
        constraints:
          - ${MAIL_PLACEMENT_CONSTRAINT:-node.hostname == node}
      resources:
        limits:
          cpus: '${MAIL_LIMITS_CPUS:-0.1}'
          memory: ${MAIL_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${MAIL_RESERVATIONS_CPUS:-0.001}'
          memory: ${MAIL_RESERVATIONS_MEMORY:-8M}

networks:
  mail-net:
    name: ${MAIL_NET_NAME:-mail-net}
    driver: overlay
    attachable: ${MAIL_NET_ATTACHABLE:-true}

volumes:
  data-vol:
    name: ${MAIL_DATA_VOL_NAME:-mail-data-vol}

  dkim-vol:
    name: ${MAIL_DKIM_VOL_NAME:-mail-dkim-vol}

  log-vol:
    name: ${MAIL_LOG_VOL_NAME:-mail-log-vol}
