version: '3.7'

services:
  mail:
    image: ${IMAGE_NAME:-marvambass/versatile-postfix}:${IMAGE_TAG:-latest}
    command: ${PUBLIC_HOSTNAME} ${MAIL_USER}:${MAIL_PASS}
    environment:
      ALIASES: postmaster:${MAIL_USER};hostmaster:${MAIL_USER};webmaster:${MAIL_USER};admin:${MAIL_USER};abuse:${MAIL_USER};${MAIL_USER}:${EXTERNAL_EMAIL_ADDRESS};${ADDITIONAL_ALIASES}
    networks:
      - mail-net
    ports:
      - target: 25
        published: ${MAIL_PORT:-25}
        mode: ${MAIL_PORT_MODE:-ingress}
    volumes:
      - mail-vol:/var/mail
      - dkim-vol:/etc/postfix/dkim/
    deploy:
      mode: replicated
      replicas: ${MAIL_REPLICAS:-1}
      restart_policy:
        delay: ${MAIL_RESTART_POLICY_DELAY:-10s}
        window: ${MAIL_RESTART_POLICY_WINDOW:-1m}
      resources:
        limits:
          cpus: '${MAIL_LIMITS_CPUS:-0.1}'
          memory: ${MAIL_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${MAIL_RESERVATIONS_CPUS:-0.001}'
          memory: ${MAIL_RESERVATIONS_MEMORY:-8M}

networks:
  mail-net:
    name: ${MAIL_NET_NAME:-mail-net}
    driver: overlay
    attachable: ${MAIL_NET_ATTACHABLE:-true}

volumes:
  mail-vol:
    name: ${MAIL_VOL_NAME:-mail-vol}
    driver: local
    driver_opts:
      type: ${MAIL_VOLUME_TYPE}
      o: ${MAIL_VOLUME_OPTIONS}
      device: ${MAIL_VOLUME_DEVICE}

  dkim-vol:
    name: ${DKIM_VOL_NAME:-dkim-vol}
    driver: local
    driver_opts:
      type: ${DKIM_VOLUME_TYPE}
      o: ${DKIM_VOLUME_OPTIONS}
      device: ${DKIM_VOLUME_DEVICE}
